### ISSUE TITLE
Few more issues/bugs

### ISSUE THREAD

**Issue by ForcePower** [srmeier/KnightOnline#10]
1)"X" (escape) button is not working seems we need to add this manually 
2) same goes for "B" Button which is work for target the near npc behind you.
3)"H" button is not working seems again we need to add this and add ui H menu.
4) You can't buy anything from npcs but in particular if u buy potion from a npc the game server nd client will crash saying moradontax is nullptr we will need to take a look in the gameserver function as well in the client.
5) While you kill monsters excpet from "Worm" all the others dont drop anything besides money and u dont see the Box of the drop - in the first place u was able to loot the money but it didnt notifcate that u get any but I fixed that on my latest commits but the aboves bugs are still remains I hope i will have time to continue working in this very weekend.

**Comment by ForcePower** [comment]
I wrote everything from my memory due the fact I need to set-up all the envorminet once again... 
atm I am focus on study in particular math as you know Stephen :)

**Comment by srmeier** [comment]
No problem ForcePower! Thanks for taking the time to write these out. Hopefully I can take a look at some of these this weekend.

**Comment by onurcanbektas** [comment]
The last 3 of the problems had already been solved when I was still active on the project, if the situation is the same in Stephen's setup, you might compare the current project with the fork of mine, which is not changed since I left.

**Comment by srmeier** [comment]
@onurcanbektas  Good point, I'll take a look at your fork first.

@ForcePower I'm not sure why only Worms are dropping things for you. I've gone into CZ and killed bosses to get boss drops before, seems to work fine. The boxes aren't showing up because the source client doesn't render them at all. This would have to be added but should be too much work. This would actually be a great first exercise in adding new graphics functionality to the source client.

**Comment by onurcanbektas** [comment]
About the clan issue, I just now tested.Creating and disbanding clan in moradan & lufer is working without any problem.

**Comment by ForcePower** [comment]
@onurcanbektas @srmeier Onur indeed solve the clan issue but as if we want to stick to the originial way of clan system so it goes like it:
1) You can only create and disband clan in Luf/EMC however, In moradon the leader can add/kick people as he wish and assist can add people while now after @onurcanbektas  you can create clan in moradon which is wrong.

**Comment by twostars** [comment]
This issue was moved to ApexKO/OpenKO#10
