### ISSUE TITLE
Issues with DirectX in N3ME

### ISSUE THREAD

**Issue by srmeier** [srmeier/KnightOnline#11]
The GUI for the N3 Map Editor is having issues rendering the DirectX scene.

A few notes:
- DX gets initiated in CMainFrame::OnCreate()
- If you prevent the DX initiation CN3MEView::OnDraw() gets called, otherwise it doesn't seem to

Anyone looking into this will need a version of VS6.

**Comment by srmeier** [comment]
Now that I think about it I need to check and see if this issue is due to SDL2 (although I'm not sure if we use the updated N3Base for N3ME).

**Comment by srmeier** [comment]
Closing this for now since we no longer have the map editor in the repo.

**Comment by twostars** [comment]
This issue was moved to ApexKO/OpenKO#11
