### ISSUE TITLE
User gets kicked after starting beginner's quest

### ISSUE THREAD

**Issue by srmeier** [srmeier/KnightOnline#12]
The player gets kicked after starting the beginner's quest in Moradon. Here I'm using the source server + binary client on an Orc Rogue.

Binary client players typically get kicked when the server sends a "SendDebugString" to the player via LUA script. For the source client this LUA function sends a packet containing the debug string which gets added to the info panel.

So we are most likely missing a EVT to LUA function conversion here.

**Comment by srmeier** [comment]
The player still has the quest after logging back into the server so everything on the server appears to be working fine. Currently looking into the EVT flag we are missing in the EVT converter.

**Comment by srmeier** [comment]
Flag STATE_CHANGE is what is missing. The EXT code looks like:

E STATE_CHANGE 8 1

**Comment by twostars** [comment]
This issue was moved to ApexKO/OpenKO#12
