### ISSUE TITLE
Issue equipping Rogue Shirt (+3)

### ISSUE THREAD

**Issue by srmeier** [srmeier/KnightOnline#13]
Level 4 Rogue Orc is having issues equipping the Rogue Shirt (+3) item. I have a feeling that the item has a level requirement which doesn't show up in the item description, so the player goes to equip the item but the server rejects the request to equip because the player isn't high enough level. Need to find the function which gets called when the server receives the packet for equipping an item.

**Comment by srmeier** [comment]
In the database this item has "Num = 241001503" and "ReqLevel = 5", but the (binary) client doesn't show this requirement so the player thinks they are able to equip it - but if they try they won't be able to.

**Comment by srmeier** [comment]
Going to try with the binary server and see if I'm able to equip this item. Ran into issue where the server IP in the database wasn't set to 127.0.0.1 so I could connect to the binary server but it's fixed now.

The binary server allows the player to equip the Rogue Shirt (even though the DB requires lvl 5) so for the time being we are going to ignore the level requirements until we have a better understanding of how the item level requirements work.

**Comment by twostars** [comment]
This issue was moved to ApexKO/OpenKO#13
