### ISSUE TITLE
Hello SetText Error null

### ISSUE THREAD

**Issue by KiraAmora61** [srmeier/KnightOnline#133]
![image](https://user-images.githubusercontent.com/27152392/58893890-ae413b00-86f9-11e9-92f1-f2f2627a2b00.png)

Old

void CUIMessageBox::SetText(const std::string& szMsg)
{
	m_pText_Message->SetString(szMsg);
}

void CUIMessageBox::SetTitle(const std::string& szTitle)
{
	m_pText_Title->SetString(szTitle);
}

New now

void CUIMessageBox::SetText(const std::string& szMsg)
{
	if (NULL == m_pText_Message)
		return;

	m_pText_Message->SetString(szMsg);
}

void CUIMessageBox::SetTitle(const std::string& szTitle)
{
	if (NULL == m_pText_Title)
		return;

	m_pText_Title->SetString(szTitle);
}

Is it true?  -now thanks <3

**Comment by onurcanbektas** [comment]
What is the question exactly ?,

**Comment by KiraAmora61** [comment]
@onurcanbektas bang problem

**Comment by twostars** [comment]
You might look into why the control's not loaded here, because that seems like more of a problem than the fact it's crashing.

**Comment by KiraAmora61** [comment]
@twostars yes Can I get a skype address

**Comment by twostars** [comment]
If m_pText_Message is nullptr it means the control's not loaded, which means either the UI needs updating or it's being used for a specialisation of a messagebox UI that isn't named the same.

You don't show a callstack here so I can't tell which instance is theoretically being used here, and I don't recall if there were changes in the naming for this UI, but it should be fairly straightforward to find out.
Load up the relevant UI in the UI editor and check what it's called, or just set a breakpoint there & check the names of the loaded children.

Checking if it's set stops it from crashing, but a messagebox without a message kind've defeats the purpose of said messagebox, so you should really find out why the control isn't attached here.

**Comment by twostars** [comment]
This is only used by the 1 UI in the official/provided assets; el_messagebox_us/ka_messagebox_us.uif, where this exists and is loaded correctly.

I'm assuming - as I did back in 2019 - the original issue occurred because this UI was reused for another variation of the UI (e.g. Co_MsgBoxOk_us.uif) which doesn't have this control, but this was never clarified. Either way, this change isn't really necessary here if using the correct client data so I'm closing this issue.
