### ISSUE TITLE
NPC Attack Basis

### ISSUE THREAD

**Issue by etatbak** [srmeier/KnightOnline#135]
Hello, I checked the codes but couldn't find the answer. I need to understand how attacking system works in Knight Online NPCs and monsters. Someone could show which codes represent these details?

**Comment by onurcanbektas** [comment]
@etatbak why should we do that ? Clearly, if you have tried and failed, you would have some specific question, which I don't see any in the above comment, so why should we spend our time to explain those things to you even you don't spend enough time to learn those things by yourself ?

**Comment by srmeier** [comment]
@etatbak I'm guessing you probably want something like this:
https://github.com/srmeier/KnightOnline/blob/e3ca5d6cc88e0b574677d27807e1554177298989/Server/AIServer/Npc.cpp#L430
