### ISSUE TITLE
Archer skills with more than 1 arrow bugged

### ISSUE THREAD

**Issue by mo3head** [srmeier/KnightOnline#136]
"Multiple Shot" as well as "Arrow Shower" lead to an exception.

It breaks on 

> uint32_t CMagicSkillMng::GetMagicID(int idx)
{
	std::map<int, uint32_t>::iterator it = m_MySelf.find(idx);
	return it->second;
}

idx is set to a value that isn't available in m_MySelf.

I haven't tinkered with any C/C++ code in at least 6 years and have never looked a the client source before but I might as well start here.

**Comment by darimuhittin** [comment]
Why the issue closed ? @mo3head
