### ISSUE TITLE
some help ? (not run)

### ISSUE THREAD

**Issue by RafailStratiotis** [srmeier/KnightOnline#139]
i try to run this project and i can't...
I have been trying for 2 days but nothing is happening..
I followed all the steps from the video
I also did a new windows installation on a new ssd
but again i could not run...

can somebody help me?

I read that the code has bugs and others but to me it does not run at all like the BitShift video....

**Comment by KiraAmora61** [comment]
Hello,

**Comment by srmeier** [comment]
Can you specify the error you're encountering in more detail?
