### ISSUE TITLE
UIE Editor "failed to create empty document."

### ISSUE THREAD

**Issue by selcukcukur** [srmeier/KnightOnline#141]
I performed the UIE Editor compilation process without any problems. At the end of a long struggle. But right now when I open the application, I see "failed to create empty document." comes a screen saying.

Do you have an opinion on this?

**Comment by selcukcukur** [comment]
Debug Info : 

'UIE.exe' (Win32): Loaded 'D:\Game-Project2\Source-Editor\UIE\UIE.exe'. Symbols loaded.
'UIE.exe' (Win32): Loaded 'C:\Windows\SysWOW64\ntdll.dll'. Cannot find or open the PDB file.
'UIE.exe' (Win32): Loaded 'C:\Windows\SysWOW64\kernel32.dll'. Cannot find or open the PDB file.
'UIE.exe' (Win32): Loaded 'C:\Windows\SysWOW64\KernelBase.dll'. Cannot find or open the PDB file.
'UIE.exe' (Win32): Loaded 'C:\Windows\SysWOW64\user32.dll'. Cannot find or open the PDB file.
'UIE.exe' (Win32): Loaded 'C:\Windows\SysWOW64\win32u.dll'. Cannot find or open the PDB file.
'UIE.exe' (Win32): Loaded 'C:\Windows\SysWOW64\gdi32.dll'. Cannot find or open the PDB file.
'UIE.exe' (Win32): Loaded 'C:\Windows\SysWOW64\gdi32full.dll'. Cannot find or open the PDB file.
'UIE.exe' (Win32): Loaded 'C:\Windows\SysWOW64\msvcp_win.dll'. Cannot find or open the PDB file.
'UIE.exe' (Win32): Loaded 'C:\Windows\SysWOW64\ucrtbase.dll'. Cannot find or open the PDB file.
'UIE.exe' (Win32): Loaded 'C:\Windows\SysWOW64\advapi32.dll'. Cannot find or open the PDB file.
'UIE.exe' (Win32): Loaded 'C:\Windows\SysWOW64\msvcrt.dll'. Cannot find or open the PDB file.
'UIE.exe' (Win32): Loaded 'C:\Windows\SysWOW64\sechost.dll'. Cannot find or open the PDB file.
'UIE.exe' (Win32): Loaded 'C:\Windows\SysWOW64\rpcrt4.dll'. Cannot find or open the PDB file.
'UIE.exe' (Win32): Loaded 'C:\Windows\SysWOW64\sspicli.dll'. Cannot find or open the PDB file.
'UIE.exe' (Win32): Loaded 'C:\Windows\SysWOW64\cryptbase.dll'. Cannot find or open the PDB file.
'UIE.exe' (Win32): Loaded 'C:\Windows\SysWOW64\bcryptprimitives.dll'. Cannot find or open the PDB file.
'UIE.exe' (Win32): Loaded 'C:\Windows\SysWOW64\shell32.dll'. Cannot find or open the PDB file.
'UIE.exe' (Win32): Loaded 'C:\Windows\SysWOW64\cfgmgr32.dll'. Cannot find or open the PDB file.
'UIE.exe' (Win32): Loaded 'C:\Windows\SysWOW64\SHCore.dll'. Cannot find or open the PDB file.
'UIE.exe' (Win32): Loaded 'C:\Windows\SysWOW64\combase.dll'. Cannot find or open the PDB file.
'UIE.exe' (Win32): Loaded 'C:\Windows\SysWOW64\windows.storage.dll'. Cannot find or open the PDB file.
'UIE.exe' (Win32): Loaded 'C:\Windows\SysWOW64\profapi.dll'. Cannot find or open the PDB file.
'UIE.exe' (Win32): Loaded 'C:\Windows\SysWOW64\powrprof.dll'. Cannot find or open the PDB file.
'UIE.exe' (Win32): Loaded 'C:\Windows\SysWOW64\umpdc.dll'. Cannot find or open the PDB file.
'UIE.exe' (Win32): Loaded 'C:\Windows\SysWOW64\shlwapi.dll'. Cannot find or open the PDB file.
'UIE.exe' (Win32): Loaded 'C:\Windows\SysWOW64\kernel.appcore.dll'. Cannot find or open the PDB file.
'UIE.exe' (Win32): Loaded 'C:\Windows\SysWOW64\cryptsp.dll'. Cannot find or open the PDB file.
'UIE.exe' (Win32): Loaded 'C:\Windows\SysWOW64\oleaut32.dll'. Cannot find or open the PDB file.
'UIE.exe' (Win32): Loaded 'D:\Game-Project2\Source-Editor\UIE\SDL2.dll'. Module was built without symbols.
'UIE.exe' (Win32): Loaded 'C:\Windows\SysWOW64\imm32.dll'. Cannot find or open the PDB file.
'UIE.exe' (Win32): Loaded 'C:\Windows\SysWOW64\ole32.dll'. Cannot find or open the PDB file.
'UIE.exe' (Win32): Loaded 'C:\Windows\SysWOW64\mfc140.dll'. Cannot find or open the PDB file.
'UIE.exe' (Win32): Loaded 'C:\Windows\SysWOW64\msvcp140.dll'. Cannot find or open the PDB file.
'UIE.exe' (Win32): Loaded 'C:\Windows\SysWOW64\vcruntime140.dll'. Cannot find or open the PDB file.
'UIE.exe' (Win32): Loaded 'C:\Windows\SysWOW64\winmm.dll'. Cannot find or open the PDB file.
'UIE.exe' (Win32): Loaded 'C:\Windows\SysWOW64\d3d9.dll'. Cannot find or open the PDB file.
'UIE.exe' (Win32): Loaded 'C:\Windows\SysWOW64\D3DX9_43.dll'. Cannot find or open the PDB file.
'UIE.exe' (Win32): Loaded 'C:\Windows\SysWOW64\dsound.dll'. Cannot find or open the PDB file.
'UIE.exe' (Win32): Loaded 'C:\Windows\SysWOW64\version.dll'. Cannot find or open the PDB file.
'UIE.exe' (Win32): Loaded 'C:\Windows\SysWOW64\uxtheme.dll'. Cannot find or open the PDB file.
'UIE.exe' (Win32): Loaded 'C:\Windows\SysWOW64\winmmbase.dll'. Cannot find or open the PDB file.
'UIE.exe' (Win32): Loaded 'C:\Windows\SysWOW64\dwmapi.dll'. Cannot find or open the PDB file.
'UIE.exe' (Win32): Loaded 'C:\Windows\SysWOW64\DXCore.dll'. Cannot find or open the PDB file.
'UIE.exe' (Win32): Loaded 'C:\Windows\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_5.82.18362.1379_none_bb62dc01ec8ffbb7\comctl32.dll'. Cannot find or open the PDB file.
'UIE.exe' (Win32): Loaded 'C:\Windows\SysWOW64\igdumdim32.dll'. Cannot find or open the PDB file.
'UIE.exe' (Win32): Loaded 'C:\Windows\SysWOW64\setupapi.dll'. Cannot find or open the PDB file.
'UIE.exe' (Win32): Loaded 'C:\Windows\SysWOW64\bcrypt.dll'. Cannot find or open the PDB file.
'UIE.exe' (Win32): Loaded 'C:\Windows\System32\DriverStore\FileRepository\nvtdi.inf_amd64_14200008c8fee7c0\nvdlist.dll'. Cannot find or open the PDB file.
'UIE.exe' (Win32): Unloaded 'C:\Windows\System32\DriverStore\FileRepository\nvtdi.inf_amd64_14200008c8fee7c0\nvdlist.dll'
'UIE.exe' (Win32): Unloaded 'C:\Windows\SysWOW64\setupapi.dll'
'UIE.exe' (Win32): Unloaded 'C:\Windows\SysWOW64\igdumdim32.dll'
'UIE.exe' (Win32): Loaded 'C:\Windows\System32\DriverStore\FileRepository\nvtdi.inf_amd64_14200008c8fee7c0\nvldumd.dll'. Cannot find or open the PDB file.
'UIE.exe' (Win32): Loaded 'C:\Windows\SysWOW64\crypt32.dll'. Cannot find or open the PDB file.
'UIE.exe' (Win32): Loaded 'C:\Windows\SysWOW64\msasn1.dll'. Cannot find or open the PDB file.
'UIE.exe' (Win32): Loaded 'C:\Windows\SysWOW64\wintrust.dll'. Cannot find or open the PDB file.
'UIE.exe' (Win32): Loaded 'C:\Windows\SysWOW64\imagehlp.dll'. Cannot find or open the PDB file.
'UIE.exe' (Win32): Loaded 'C:\Windows\SysWOW64\rsaenh.dll'. Cannot find or open the PDB file.
'UIE.exe' (Win32): Loaded 'C:\Windows\System32\DriverStore\FileRepository\nvtdi.inf_amd64_14200008c8fee7c0\nvd3dum.dll'. Cannot find or open the PDB file.
'UIE.exe' (Win32): Unloaded 'C:\Windows\System32\DriverStore\FileRepository\nvtdi.inf_amd64_14200008c8fee7c0\nvldumd.dll'
'UIE.exe' (Win32): Loaded 'C:\Windows\SysWOW64\msctf.dll'. Cannot find or open the PDB file.
'UIE.exe' (Win32): Unloaded 'C:\Windows\System32\DriverStore\FileRepository\nvtdi.inf_amd64_14200008c8fee7c0\nvd3dum.dll'
The thread 0x1198 has exited with code 0 (0x0).
'UIE.exe' (Win32): Loaded 'C:\Windows\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.18362.1379_none_e62d2a8af8d8e9ca\comctl32.dll'. Cannot find or open the PDB file.
'UIE.exe' (Win32): Loaded 'C:\Windows\SysWOW64\TextInputFramework.dll'. Cannot find or open the PDB file.
'UIE.exe' (Win32): Loaded 'C:\Windows\SysWOW64\CoreMessaging.dll'. Cannot find or open the PDB file.
'UIE.exe' (Win32): Loaded 'C:\Windows\SysWOW64\CoreUIComponents.dll'. Cannot find or open the PDB file.
'UIE.exe' (Win32): Loaded 'C:\Windows\SysWOW64\ntmarta.dll'. Cannot find or open the PDB file.
'UIE.exe' (Win32): Loaded 'C:\Windows\SysWOW64\WinTypes.dll'. Cannot find or open the PDB file.
'UIE.exe' (Win32): Loaded 'C:\Windows\SysWOW64\WinTypes.dll'. Cannot find or open the PDB file.
'UIE.exe' (Win32): Unloaded 'C:\Windows\SysWOW64\WinTypes.dll'
'UIE.exe' (Win32): Loaded 'C:\Windows\SysWOW64\iertutil.dll'. Cannot find or open the PDB file.
'UIE.exe' (Win32): Loaded 'C:\Windows\SysWOW64\igdumdim32.dll'. Cannot find or open the PDB file.
'UIE.exe' (Win32): Loaded 'C:\Windows\SysWOW64\setupapi.dll'. Cannot find or open the PDB file.
'UIE.exe' (Win32): Unloaded 'C:\Windows\SysWOW64\setupapi.dll'
'UIE.exe' (Win32): Unloaded 'C:\Windows\SysWOW64\igdumdim32.dll'
'UIE.exe' (Win32): Loaded 'C:\Windows\System32\DriverStore\FileRepository\nvtdi.inf_amd64_14200008c8fee7c0\nvldumd.dll'. Cannot find or open the PDB file.
'UIE.exe' (Win32): Loaded 'C:\Windows\System32\DriverStore\FileRepository\nvtdi.inf_amd64_14200008c8fee7c0\nvd3dum.dll'. Cannot find or open the PDB file.
The thread 0x2678 has exited with code 0 (0x0).
'UIE.exe' (Win32): Unloaded 'C:\Windows\System32\DriverStore\FileRepository\nvtdi.inf_amd64_14200008c8fee7c0\nvd3dum.dll'
'UIE.exe' (Win32): Unloaded 'C:\Windows\System32\DriverStore\FileRepository\nvtdi.inf_amd64_14200008c8fee7c0\nvldumd.dll'

**Comment by selcukcukur** [comment]
The problem was solved with a few minor adjustments. Good work.

**Comment by KiraAmora61** [comment]
Can you talk about how he solved it?

**Comment by selcukcukur** [comment]
First of all, I separated the project from the SDL library. Then I took a look at the original version of the project and re-prepared it in the way that DirectX directly communicated with the windows libraries. I checked for DirectX version incompatibilities and got the library files of the current DirectX version and included them in the project. Finally, I made major changes to n3base. I have now finally made all NoahSystem editors buildable. 

- N3CE
- N3FXE
- N3Indoor
- N3ME
- N3TexViewer
- N3Viewer
- Option
- RSCTables
- ServerInfoViewer
- SkyViewer
- Plugin_Maya
- Plugin_3DMax

 My checks are finally running smoothly, all I have to do is make the updates to support the up-to-date files.

**Comment by KiraAmora61** [comment]
@selcukcukur Hello,

 I installed all of them, I am getting more than error

thank you for answering.

**Comment by selcukcukur** [comment]
> @selcukcukur Hello,
> 
> I installed all of them, I am getting more than error
> 
> thank you for answering.

You cannot compile directly, which requires a lot of fixes for compatibility.

**Comment by KiraAmora61** [comment]
@selcukcukur Hello,

How can I fix it is there any chance to help?

thank you for answering.

**Comment by selcukcukur** [comment]
> @selcukcukur Hello,
> 
> How can I fix it is there any chance to help?
> 
> thank you for answering.

Soon I will start developing all files as open source. You can follow me.

**Comment by KiraAmora61** [comment]
where do we start?
