### ISSUE TITLE
UİF Source poblem !

### ISSUE THREAD

**Issue by KiraAmora61** [srmeier/KnightOnline#142]
Thnsk

**Comment by muratoflu** [comment]
Seems like you are compiling the N3Base library with MT (multi threaded static link) flag whereas the linker properties for UIE expects it to be a MD (multi threaded dynamic link) project. 

You'll most likely need to compile the base project with either type of the flag (Dynamic link library or Static) and keep using the same for all other libraries that link towards the base.

**Comment by KiraAmora61** [comment]
Hello @muratoflu 

some i am having a problem but i couldn't solve
![image](https://user-images.githubusercontent.com/27152392/114319047-73d82e80-9b18-11eb-8f83-e43f57b4f6d8.png)

> Seems like you are compiling the N3Base library with MT (multi threaded static link) flag whereas the linker properties for UIE expects it to be a MD (multi threaded dynamic link) project.
> 
> You'll most likely need to compile the base project with either type of the flag (Dynamic link library or Static) and keep using the same for all other libraries that link towards the base.

**Comment by KiraAmora61** [comment]
is there anyone to help? 

@onurcanbektas @srmeier @twostars
