### ISSUE TITLE
WarFare.exe

### ISSUE THREAD

**Issue by xMaikey** [srmeier/KnightOnline#144]
Hello, if I want to run warfare, it shows me this error.
It means that system could not find knightonline.exe

Any help please ?
![image](https://user-images.githubusercontent.com/121102786/208667810-6536a3a6-7e69-4309-af64-bc44c474baaf.png)

As I could see on your videos you have all data files. Is it possible to share them if you still have them of course :)
![image](https://user-images.githubusercontent.com/121102786/208679674-a155bca6-e82e-4c0a-bccd-a1c281b47bf3.png)

**Comment by srmeier** [comment]
Does the project compile for you without errors?

**Comment by twostars** [comment]
And if it has compiled, make sure Windows Defender isn't actively blocking it. You might want to just exempt the entire folder.
It really hates KO.

**Comment by burdem** [comment]
same here. data folder is missing in Client folder.

**Comment by twostars** [comment]
> same here. data folder is missing in Client folder.

This is because you're expected to include your own (originally 1.264 but I think it was probably bumped up to 1.298?) client assets there, rather than bloat the repository and cause it to perform horrendously.

**Comment by burdem** [comment]
Well, I just followed to instructions on here: https://www.youtube.com/watch?v=bm36CvJX9to
Just for try, I've copied a data folder from another client. Then I started new instance of WarFare. Exe started but frozen immediatly and the cursor stucked on the hourglass. (AIServer, GameServer, LoginServer works fine)

**Comment by srmeier** [comment]
That video is pretty old. I need to make an updated version.

**Comment by xMaikey** [comment]
Are you guys still developing this project ? i would like to see :)
@Burdem do you use correct Visual studio? 

Asking because i found another publisher and his video how to create game and run it. 
However he used VS 2017 and VS 2019 and if it try it on 2022 it does not work xD

**Comment by burdem** [comment]
@srmeier that would be really nice. Some people may give up if they can not find a proper documentation or instruction videos. This project needs more attention and contribution :) 

@xMaikey I am using VS 2019 and it works fine.
