### ISSUE TITLE
D3DX8.h error

### ISSUE THREAD

**Issue by akbalburak** [srmeier/KnightOnline#145]
Guys, Map editor is asking for D3Dx8 file. How can I fix this?

**Comment by twostars** [comment]
With the above commit now including DX8.1 (+ MFC2013 -- the last version that still used DX8), N3ME should build now.

It is, however, barely touched -- and its N3Base folder seems to be a lesser maintained clone of the original N3Base folder used by the client, so it is certainly in an interesting place.
