### ISSUE TITLE
Issue buying arrows from Rudien Sundries

### ISSUE THREAD

**Issue by srmeier** [srmeier/KnightOnline#15]
This is likely a similar issue as the previous issue with the potion merchant. Looking into this, probably just a packet thing.

**Comment by srmeier** [comment]
Ok, interestingly the binary client doesn't send GROUP or NPCID for TYPE==2 NPCs but it does for TYPE==1 NPCs. The packets have been updated on the server side. I need to check these packets for the source client to make sure they match up and we should be good to go on this.

**Comment by twostars** [comment]
This issue was moved to ApexKO/OpenKO#15
