### ISSUE TITLE
Some issues with the standard EVT codes

### ISSUE THREAD

**Issue by srmeier** [srmeier/KnightOnline#16]
So the original EVTs for zone 21 (Moradon) have some incorrect codes. What the NPC says (things like "you have to be level 10 or above" or "would you like to retry this quest") doesn't match up with what actually happens in the EVTs. This isn't an issue with the converter because the LUA code matches what the EVTs say to do but the EVTs are just wrong.

This issue is just for NPC Isaac in Moradon but unfortunately I'm sure this is an issue all over the place...

**Comment by onurcanbektas** [comment]
We can use edited EVTs of other servers ? They probably have already fix it.

**Comment by srmeier** [comment]
Absolutely, if you are able to find any just drop them in the repo

**Comment by onurcanbektas** [comment]
There were all in my deleted VM :).I will send a forum that you can look for those kind of files through whatsapp, but in case you can't find it, I can handle with it when I come back.

**Comment by twostars** [comment]
This issue was moved to ApexKO/OpenKO#16
