### ISSUE TITLE
LoginServer pulls from static / hardcoded LoginServer.ini versus dbo.SERVERS

### ISSUE THREAD

**Issue by wwrighter** [srmeier/KnightOnline#19]
Current setup of LoginServer is setup in LoginServer.cpp and hardcoded to populate the LoginServer.ini (see debug/release bin).  

**References:**
LoginServer.cpp : void LoginServer::GetInfoFromIni()
UILogin.h : struct __GameServerInfo : public binary_function<__GameServerInfo, __GameServerInfo, bool>

**Assumptions:**
Populate LoginServer list using dbo.SERVERS table from KN_online database instead of ./LoginServer.ini (CONF_LOGIN_SERVER)

**Comment by srmeier** [comment]
Looking over this I think we could create a CServersSet class which inherits from OdbcRecordset and grab the rows from SQL server that way (an example would be the CServerResourceSet class located in "./KnightOnline/Server/shared/database/"). At this point we would have the data loaded from SQL server and could add it to LoginServer's "m_ServerList". However the "_SERVER_INFO" structure has other members such as strKarusKingName, strElMoradKingName, etc.. these aren't in the same table and could possibly be left the way they are for the time being.

**Comment by twostars** [comment]
This issue was moved to ApexKO/OpenKO#19
