### ISSUE TITLE
Issue with users missing "AfxVer_.h"

### ISSUE THREAD

**Issue by srmeier** [srmeier/KnightOnline#20]
User "Lost" of the forums came to me with the issue:

"Cannot open include file: 'AfxVer_.h': No such file or directory"

This was a simple fix by just commenting out almost everything in "StdAfxBase.h". We don't use most of that stuff anyways.

**Comment by onurcanbektas** [comment]
I wonder why is that happened in his setup whereas I did the setup at least 3 time, and I have never faced such a thing.

**Comment by srmeier** [comment]
Yeah, I've never had this problem either. He gave me his teamviewer info and I actually looked where windows puts the AfxVer_.h header and it just wasn't there for him... My guess would be that it has something to do with the options people select (or more likely don't select) when installing VS15. It's still very strange though!

**Comment by twostars** [comment]
This issue was moved to ApexKO/OpenKO#20

**Comment by Osein** [comment]
If anybody still wondering why this error throws, it is because he didn't installed Visual Studio MFC

**Comment by onurcanbektas** [comment]
Thanks for sharing @Osein
