### ISSUE TITLE
1264 Combat packets

### ISSUE THREAD

**Issue by srmeier** [srmeier/KnightOnline#25]
There seems to be an issue with some of the combat packets for the 1264 client. My first guess would be to start investigating the WIZ_ATTACK and similar packets. This could also just be an issue with the binary client and could be a bug on MGame's part but I believe incorrect packets is a more likely scenario.

![image of info panel](http://stephenmeier.net/files/info_panel_pic.png)

**Comment by Demircivi** [comment]
I guess packet structure is different compared to 1299.

**Comment by srmeier** [comment]
somehow this has been fixed along the way. I will also say that some of the text issues had to do with 1264's text_us.tbl version being incorrect. I have updated the data.zip folder on the forums to include the 1298 version of that TBL.

**Comment by twostars** [comment]
This issue was moved to ApexKO/OpenKO#25
