### ISSUE TITLE
Matching the GetNpcInfo packet with the source client's MsgRecv_NPCIn packet

### ISSUE THREAD

**Issue by srmeier** [srmeier/KnightOnline#26]
This is a quick fix and good for someone new to the project. First find the "CNpc::GetNpcInfo" function in the Npc.cpp file of the GamerServer project. This function creates a packet containing all the Npc information to send to the client. This is the correct packet structure. Make a note of the structure of this packet and then open up GameProcMain.cpp in the WarFare project. Find the "CGameProcMain::MsgRecv_NPCIn" function and rewrite some of this code so that the client is getting exactly what the server is sending.

If you have any questions please post them here!

**Comment by twostars** [comment]
This issue was moved to ApexKO/OpenKO#26
