### ISSUE TITLE
You can't know coin amount until you loot it.

### ISSUE THREAD

**Issue by Demircivi** [srmeier/KnightOnline#35]
As you can see in the picture below, you can't know coin amount until you loot it.
![image](https://cloud.githubusercontent.com/assets/22484255/24677009/e9be5860-198d-11e7-8c7d-c9d40c652e55.png)
![image](https://cloud.githubusercontent.com/assets/22484255/24677024/fad9b5ea-198d-11e7-9cfd-5a1805164208.png)

**Comment by twostars** [comment]
This was caused by the resource hackery. Now that it's all loading up from Texts_us.tbl, this shows correctly.

**Comment by twostars** [comment]
This issue was moved to ApexKO/OpenKO#35
