### ISSUE TITLE
There is no Command window.

### ISSUE THREAD

**Issue by Demircivi** [srmeier/KnightOnline#36]
In 1299 you were able to reach commands like "/greeting" etc. from Command menu as you can see below.
By the way, when you type "/greeting" into chat screen greeting animation happens.
![image](https://cloud.githubusercontent.com/assets/22484255/24677115/59e1b600-198e-11e7-9808-11f05ed253be.png)

Of course they're many commands which were used in common.

**Comment by twostars** [comment]
This issue was moved to ApexKO/OpenKO#36

**Comment by SavvyNik** [comment]
I don't believe that the command window is being loaded into the client at all. Looks like we should make a new UI class for curtail (cmd window). I can start laying out the class and the H hotkey to open/close the window. Unless I haven't found it which I'd like confirmation that I'm not missing something.

**Comment by twostars** [comment]
It isn't implemented, no.

**Comment by SavvyNik** [comment]
Started working on this. Something goofy is happening when opening/closing dialog. Will have to add strings for commands.

[] Fix opening and closing of UI w/ 'H' key.
[] Add commands to UI window
[] Process commands

[CUICurtail Commit](https://github.com/SavvyNik/KnightOnline/commit/9804eda49bfd2205b247e34be376ab29acb3472d)

**Comment by SavvyNik** [comment]
I figured out what was going on with opening/closing of dialog. The closing and opening of dialog with 'H' key is working now, as well as, using the x close on the window.

**Comment by twostars** [comment]
I know it's minor, but the name of that class is confusing. It's not the first thing I'd think of when trying to find that UI; perhaps it should be renamed such that it's at least similarly named to its name in UIs_us.tbl, e.g. CUICmdList?

**Comment by SavvyNik** [comment]
I agree. I'll be changing the name. The reason I started with curtail is that's what it is called in the .dxt file and that's how I originally tracked it down. Lol idk what curtail even means feels like that got lost in tranlation.

**Comment by SavvyNik** [comment]
Is there an example where strings are loaded into some portion of the UI that can be selected?  I'm having trouble deciding how this should work and haven't found a good example yet.  I'm assuming I'll place the commands on icons or something of the sort.  Then when an icon (whatever) is selected load a subset of commands.  Then upon an icon subset selection, the command gets handled.

**Comment by twostars** [comment]
Huh? I don't follow.

There's 2 listboxes; one for the command groups and the other for the selected commands.
You populate the first with the command groups from the resources, and then upon selection repopulate the command list itself with the selected commands.

All of the strings are loaded via _LoadStringFromResource().

When the commands are triggered, you trigger its respective command via handler in CGameProcMain. Likewise when it should prompt for string input (e.g. for names), upon submission it should trigger the respective command there with the provided input as an argument.

If command handling via chat is in a good place (it may need to be reverted and the command order updated if not, because a lot of stuff related to resources was tampered with early on in this repo), this should be fine. If not, that also needs to be addressed independently of this UI.

**Comment by SavvyNik** [comment]
Made some progress.. it might be cleaner to create a list object for each category. Then I can load the strings in once on initialization and after that display the correct list based on what category a user selects.

[CUICmdList Commit 3](https://github.com/SavvyNik/KnightOnline/commit/11313b406e0b4a795cd5a838fd15b1f78f836735)

**Comment by SavvyNik** [comment]
@twostars I've implemented a map instead that I iterate over to pull in the text resources. Hopefully, this is a little cleaner than manually loading in each resource. 

[CUICmdList Commit 4](https://github.com/SavvyNik/KnightOnline/commit/064dacbd818e12b9bb07dc698ed166bbd742fa7a)

**Comment by twostars** [comment]
Regarding the extra commands being loaded, I wouldn't worry about them. In my implementation I just left them.

Can always just remove them from the TBL itself if they bother you, but they don't harm anything.

**Comment by SavvyNik** [comment]
I appreciate all the suggestions you made on the last commit. 

[CUICmdList Commit 5](https://github.com/SavvyNik/KnightOnline/commit/64a1b28bf9f7a0debc66b95692fed00392b4d67e)

**Comment by twostars** [comment]
```

bool CUICmdList::ReceiveMessage(CN3UIBase* pSender, uint32_t dwMsg)
{
	if (NULL == pSender) return false;

	if (dwMsg == UIMSG_BUTTON_CLICK)
	{
		if (pSender->m_szID == "btn_cancel")
			SetVisible(false);
	}
	else if (pSender == m_pList_CmdCat) {
		uint8_t iSel = m_pList_CmdCat->GetCurSel();
		UpdateCommandList(iSel);
	}
	else if (pSender == m_pList_Cmds) {
		uint8_t iSel = m_pList_Cmds->GetCurSel();
		ExecuteCommand(iSel);
	}
	
	return false;
}
```
Each individual case here that handles the event should be returning true.
Additionally, it should default back to passing it to CN3UIBase::ReceiveMessage() so it can feed it back up the chain.

Finally, these cases:
```
	else if (pSender == m_pList_CmdCat) {
		uint8_t iSel = m_pList_CmdCat->GetCurSel();
		UpdateCommandList(iSel);
	}
	else if (pSender == m_pList_Cmds) {
		uint8_t iSel = m_pList_Cmds->GetCurSel();
		ExecuteCommand(iSel);
	}
```

These need to be more specific about the event we're actually handling here, e.g.:
```
	else if (dwMsg == UIMSG_LIST_SELCHANGE)
	{
		// Changed the selected group
		if (pSender == m_pGroupList)
			UpdateList(GetSelectedGroup());
	}
	else if (dwMsg == UIMSG_LIST_DBLCLK)
	{
		// Double-clicked a command
		if (pSender == m_pCommandList)
			SelectCommand(GetSelectedCommand());
	}
```
(I was lazy and just copied it straight from mine, so don't mind that :P)

**Comment by SavvyNik** [comment]
@twostars what was the artist/station you were listening to earlier on your last twitch stream? It was good haha I'd like to hear more.

**Comment by twostars** [comment]
Can you be more specific? Just goes through Youtube's suggestions, but if I had an idea of which song (I was streaming for 8 hours, lol) I can probably narrow it down.

**Comment by SavvyNik** [comment]
The reason I couldn't get any more specific is that I had no clue what was being said and I liked it all haha. It was like Japanese or Chinese pop music. I figured you were streaming some station. Wasn't looking for a specific song just the station 😄

**Comment by twostars** [comment]
Was probably Kana Nishino (nightcore version) then.

**Comment by SavvyNik** [comment]
That's it! Haha alright sorry for spamming here I was too interested ><

**Comment by SavvyNik** [comment]
Added in a new class and made some slight changes to CUICmdList. Starting to get things functioning together. Commands are being sent down to the chat command handler. Seems to work at least the commands that are being handled.

[Commit 6](https://github.com/SavvyNik/KnightOnline/commit/89b7440d8e6c773bc14d6ccbf7d2fb9fa81fe49c)

**Comment by SavvyNik** [comment]
We can close this one.
