### ISSUE TITLE
Client doesn't register items into Hotkey Window when you right click them.

### ISSUE THREAD

**Issue by Demircivi** [srmeier/KnightOnline#39]
Items can be registered to that window manually. But right clicking was important in my opinion.
![image](https://cloud.githubusercontent.com/assets/22484255/24677411/698ebfde-198f-11e7-8100-4e5d525f78fd.png)

**Comment by twostars** [comment]
This issue was moved to ApexKO/OpenKO#39

**Comment by d5dl2** [comment]
This issue still exists. Sometimes right clicking works, sometimes it wont work.
