### ISSUE TITLE
After completing a skill quest, e.g 70 skill, there is no data sent to server in order to save the status

### ISSUE THREAD

**Issue by onurcanbektas** [srmeier/KnightOnline#4]
In Lua scripts, the corresponding event just checks the the necessary item, robs them and save the quest to the state 2 and that is it, but somehow client know that and does the skills available to the user.However, since there is no data sending and saving, after re-login, the skills becomes unavailable again.

What is or what should be the logic in here ? Any idea would help.

Note that, I'm using binary client.

The reason why I am writing in here is that since it a open source project, the important discussions should also be open to everyone, I think.

**Comment by srmeier** [comment]
Yes, this is a perfect place to post this kinda stuff. Do you happen to know the event id for this? Also, what's the zone and what is your class/gender/race?

**Comment by onurcanbektas** [comment]
EventID : 6010 , Class: 112 (Mastered Priest) , Zone: 1, Race : Karus

**Comment by onurcanbektas** [comment]
By the way, I kinda discovered something :).Since, the skill data is, somehow, sent to client.While updating the user data, I guess it happens every 5 min, the skill data also can be saved to the database although it is clearly not a good way to do that.

**Comment by srmeier** [comment]
K, good to know. I'll have a look at this

**Comment by onurcanbektas** [comment]
Addition to my previous comment, a couple of minutes after earning the skill through the quest, the skill becomes unavailable to use again, which, I assume, happens when the user data is updated to database (exec UPDATE_USER_DATA).Therefore, we can confidently say that there is no info sent to client, but somehow and very weirdly client knows that the quest is done and it should make the skill available to the user.

**Comment by ForcePower** [comment]
Maybe on this one we can make a hash check for both sides in order to ensure the data have been sent and stored?

**Comment by onurcanbektas** [comment]
I don't know what do you mean by hash check ? I think we should first find the part that the client sends, at least recognise the quest, because if it indeed sends the skill data to source, I don't think we have anything to process that data.If I don't remember wrong, it might be send with the packet 56, and  we don't even process the these packet in the source.

**Comment by srmeier** [comment]
Packet 0x56 is the WIZ_NPC_SAY on the server-side and N3_QUEST_TALK on the client-side. We do process these packets and the two extra DWORDs that were added to this packet might have something to do with how this feature is implemented.

void CUIQuestTalk::Open(DataPack *pDataPack, int &iOffset)

**Comment by twostars** [comment]
This issue was moved to ApexKO/OpenKO#4
