### ISSUE TITLE
F1, F2, F3 and F4 doesn't skip between pages in Hotkey Window.

### ISSUE THREAD

**Issue by Demircivi** [srmeier/KnightOnline#45]
You can only navigate with this button.
![image](https://cloud.githubusercontent.com/assets/22484255/24677793/b58d0fc0-1990-11e7-8e39-b7645f68e462.png)

**Comment by twostars** [comment]
This issue was moved to ApexKO/OpenKO#45

**Comment by d5dl2** [comment]
This issue still exists.
