### ISSUE TITLE
Issue with health option effect (Water of Favors)

### ISSUE THREAD

**Issue by srmeier** [srmeier/KnightOnline#60]
Slight issue with the casting effect for Water of Favors ([see here](https://gfycat.com/AssuredDearestAtlanticsharpnosepuffer)). However I need to test to make sure this isn't an issue with the client files themselves.

**Comment by twostars** [comment]
This issue was moved to ApexKO/OpenKO#60

**Comment by nikos32** [comment]
> Slight issue with the casting effect for Water of Favors ([see here](https://gfycat.com/AssuredDearestAtlanticsharpnosepuffer)). However I need to test to make sure this isn't an issue with the client files themselves.

This issue lies in CN3FXPartParticles::Tick() and occurs because it is handled with the wrong data type.
