### ISSUE TITLE
Suggest my review. I made simple arrangements. Version 1298 continued.

### ISSUE THREAD

**Issue by qwertyu131** [srmeier/KnightOnline#63]
https://github.com/qwertyu131/Knight-Online-Client-Source

![adsiz](https://user-images.githubusercontent.com/5955474/28415970-afd6ebfa-6d5a-11e7-8668-9e08418d2a9f.jpg)

**Comment by onurcanbektas** [comment]
"Suggest my review" ? What do you mean ?

**Comment by qwertyu131** [comment]
Onur ben mustafa herkese acık olarak paylaştım projeyi yaptıklarımı.

**Comment by twostars** [comment]
I'm not sure what you're after here, since the projects appear independent we can't directly merge in changes.

**Comment by onurcanbektas** [comment]
I have talked with him, and he said that he just wanted to let us know of his project, so this issue can be deleted.
