### ISSUE TITLE
Resource.h

### ISSUE THREAD

**Issue by SavvyNik** [srmeier/KnightOnline#71]
The id's in resource.h do not match up with the supplied Text_us.tbl file that's in Client\data\Data. Version 1298 of the Text_us.tbl matches. This causes the incorrect lookup of messages that are displayed. For example, logging in with an incorrect user displays id 2903 which is text str "Cannot equip because of your high level" instead of "No such registered ID". Replacing the Text_us.tbl with the 1298 version fixes this issue.

**Comment by onurcanbektas** [comment]
It is weird, I have never faced with such a problem.

**Comment by twostars** [comment]
This is one of the reasons I was pushing towards just using 1.298. I'd just use that set instead of the 1.264 one.

**Comment by SavvyNik** [comment]
Might not be a bad idea to upgrade because the nation select screen is still bugged as well.  The code fails to load the buttons from the uif file for the nation select screen when creating a new character.  I believe if the switch is made to 1.298 that this issue will go away as well.

**Comment by twostars** [comment]
I haven't checked, but I vaguely recall the committer mentioning something along the lines of them having to change the assets to "make it work", which is not something that we should be doing.

I know this UI works just fine (as horrible as it is) without having to touch the UIF itself, as I've fixed up this UI's logic in another project, so more than likely we just need to take a proper look at it.

**Comment by srmeier** [comment]
Ok sounds good, I'll grab the stock 1298 data files and attach them to the post on ko4life. I'll also make a post making it obvious that the data files are now 1298. After I do that would someone like to update the TBL data structures?

**Comment by SavvyNik** [comment]
@srmeier what do you mean by update the tbl data structures? Is this something in the backend code or the tbl's themselves. If you guide me in the right direction I should be able to do it.

**Comment by twostars** [comment]
It's just the structs he's referring to that match up with the TBL structure.

I think they were mostly fine; the biggest offender is just UIs_us.tbl. They may have already been tweaked here.

**Comment by SavvyNik** [comment]
Alright I can look at this then when the files get uploaded to KO4life

**Comment by srmeier** [comment]
@SavvyNik Just finished uploading the 1298 data files.
http://ko4life.net/topic/50-the-openko-project/

**Comment by SavvyNik** [comment]
Thanks. Got it and updated structures.

**Comment by SavvyNik** [comment]
@twostars I didn't realize we both updated the structures around the same time. Take a look over mine and see if we'd like to add in the missing definitions from the ui_us table instead of just filling in szIdk[SIZE];

**Comment by twostars** [comment]
Go for it. I just didn't intend to be going through everything we hadn't actually implemented, but you can for sure replace mine with yours.

**Comment by SavvyNik** [comment]
Alright, you'll have to accept my pull request then.

**Comment by twostars** [comment]
I merged them for you.
