### ISSUE TITLE
Cannot use tp gates in national towns

### ISSUE THREAD

**Issue by SavvyNik** [srmeier/KnightOnline#73]
Cannot use tp gate to get out of Berth. I'm assuming it's the same with Piana. Haven't had time to narrow it down yet.

**Comment by srmeier** [comment]
Does it say "you have selected the wrong TP gate?" I can't remember the exact reason but it might have something to do with either the database or the .smd file for the map on the server-side.

**Comment by SavvyNik** [comment]
No it does not say that in the information dialog box. I went ahead and attached a picture. What I do see is console warning from the client saying that there's an Unknown Object Event @ line 5383 of GameProcMain. 

![capture2](https://user-images.githubusercontent.com/28809065/29791277-fa6cf5ae-8c01-11e7-90e0-856f6dac4de9.PNG)

**Comment by srmeier** [comment]
k, unknown game object is likely an issue with .smd

**Comment by twostars** [comment]
This is simply a configuration issue. These work fine here.
