### ISSUE TITLE
A bug related with +give_item command while giving uncountable items while specifying the stack size other than one

### ISSUE THREAD

**Issue by onurcanbektas** [srmeier/KnightOnline#84]
To explain the problem, lets assume that when player opens the npc A, the npc take one of the fork item from the user. So lets try to give ourselves 5 forks with the command 

`+give_item test 100010000 5` 

However, this will give us only one fork, but still when I open the npc A, my fork will not be robbed by the npc. in order for my fork to be robbed I need to open the npc 5 times.

I thought, maybe I'm not seeing the other 4 fork for some reason, so I relogged, but I had still 1 fork.

Plus, I tried the same thing while having only one slot empty in my inventory, but the bug still persisted.

I couldn't do any inspection on the code about the bug (don't have time right now),  and just wanted document the bug.

**Comment by twostars** [comment]
Closing as a nonissue. This "issue" only exists when explicitly giving yourself more than 1 stack of an item that isn't stackable... which is something players aren't going to be doing (or GMs, really).

Either way, this is a server issue, not so much a client issue.
